---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hnykq8yljshb/public_html
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;